[package]
name = "gain-engine-no-gui"
version = "0.1.0"
authors = ["user"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kteach-core={path="../.."}
kteach-utils={path="../../../utils"}

[workspace]
